#!/bin/bash
path=$(gdrive_url_to_path.py "$(xclip -o -selection clipboard)")
if [ $? == 0 ]; then
    notify-send "Google Drive Path" "$path"
    echo "$path" | xclip -i -selection clipboard
else
    notify-send "Google Drive Path" "Failed to find path"
fi
